### PR TITLE
Fix changelog format

### PR DESCRIPTION
**Pull request by varshavaradarajan**

### CODE REVIEW

**Comment by varshavaradarajan** [comment]
@GaneshSPatil: can you please merge this when you're free? Thank you!

**Comment by ketan** [comment]
I don't believe we use this repo anymore, @kritika-singh3 ?

**Comment by kritika-singh3** [comment]
@ketan @varshavaradarajan This repo is used only in pipeline `go-packages` and `verify-usage-data-reporting`. For all others (release related), the code has been migrated to https://github.com/gocd/codesigning.

**Comment by varshavaradarajan** [comment]
@kritika-singh3 - can scripts that are migrated to the codesigning repo be deleted from here? Any reason for them to be kept here still?

**Comment by kritika-singh3** [comment]
@varshavaradarajan - The only reason for not deleting the scripts in question was to keep a track of what used to happen before the migration. The release pipelines and scripts are fairly stable now. So, we can go ahead and delete them.

**Pull request closed without merging**
